# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anna
title: Perpetual Learner, Doer, and STEM Enthusiast
email: 
website:

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: 
github_username:  anna-5765
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
# linkedin_username:
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
- title: Duckietown
  icon: fas fa-route
  url: https://www.duckietown.org

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: # images/something.jpg
about_content: | # this will include new lines to allow paragraphs
   Hi, my name's Anna and I'm a Mechanical Engineer. Most recently I've taken an interest in robotics & autonomy, working through the Duckietown curriculum of self-driving vehicles. I have also worked in process engineering from line-side support, capital projects, data analytics, to management. Throughout my career I've gained skills including design, test, computer programming, teamwork, and leadership. 

   I am most skilled in: <mark>Learning</mark> and <mark>Optimism</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Purdue Utility Project
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #    This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        # description: | # this will include new lines to allow paragraphs
        #    I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

      - layout: top-middle
        title: Duckietown
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
 
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Caterpillar
        link: 
        # link_text: boringcompany.com
        sub_title: 
        caption: # November 2017 - Present
       # quote: >
      #    Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: |
          ETHx: ETH Zurich
        caption: November 2022 - November 2023
        sub_title: Self-Driving Cars with Duckietown
        quote: >
          Self-Driving Cars with Duckietown is a robotics and AI Massive Open Online Course hosted on edX, an online learning platform.
        description: | # this will include new lines to allow paragraphs
          I started this course as a way of improving my technical repertoire and learning about robotics and programming. Through an intense learning approach, I gained experience with professional tools and workflows used in modern robotics such as <mark>Linux</mark> and terminal interfaces, using <mark>ROS</mark>, programming in <mark>Python</mark>, training computer vision <mark>neural networks</mark>, managing code with <mark>GitHub</mark>, incrementally developing solutions, creative troubleshooting, and testing solutions in simulation before the real world.

          I also interacted with the community of peer learners and the staff on the course Slack and Stack Overflow. This includes asking for help and supporting others in answering peer questions.
      - layout: left
        title: Purdue University
        caption: August 2014 - May 2018
        sub_title: | 
          BS Mechanical Engineering
        # quote: >
        #   insert quote text
        description: | # this will include new lines to allow paragraphs
          During my time at Purdue I learned key skills that have I have taken through my career such as dedication, an intuition to how the science of the world works, and a curiosity to creativly problem-solve. I thouroughly enjoyed my time at university.

          I spent a lot of my free time working on the Purdue Utiity Project global development team and advocating for global engineering experiences as an Ambassador for both the Office of Proffessional Practice Global Engineering Programs and the Global Engineering Alliance for Research and Education.

      - layout: left
        title: ESTACA
        caption: Spring 2017
        sub_title: Automotive & Aeronautics Design Program
        quote: >
          ESTACA (École Supérieure des Techniques Aéronautiques et de Construction Automobile) Paris campus offers this program to international applicants as a technical skill-centric program focusing on computer aided design and simulation.
        description: | # this will include new lines to allow paragraphs
          This was a study abroad semester for me that amplified my engineering basis as well as my cultural understandings.
          
          Modules included Computer Aided Design (<mark>CATIA</mark>), Signal Processing (<mark>Matlab</mark>), Computational Fluid Dynamics (<mark>STAR-CCM+</mark>), Hydraulic Systems (<mark>AmeSim</mark>), Structural Design (FEM Simulation with CATIA), Technical Project, and French Language and Culture.
  
  - title: A Little More About Me
    layout: text
    # content: | # this will include new lines to allow paragraphs
    #   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
    #   - Rock climbing
    #   - Gaming
    #   - Knitting
    #   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

    #   Look at this cool image  
    #   ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
