# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anna
title: Perpetual Learner, Do-er, and STEM Enthusiast
email: 
website:

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: 
github_username:  anna-5765
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
# linkedin_username:
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: Duckietown
#   icon: fas fa-route
#   url: https://www.duckietown.org

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/CanvaIcon.png
about_content: | # this will include new lines to allow paragraphs
   Hi, my name's Anna and I'm a Mechanical Engineer. Most recently I've taken an interest in robotics & autonomy, working through the Duckietown curriculum of self-driving vehicles. I like programming, hands-on engineering and test, and learning something new.

# I have also worked in process engineering from line-side support, capital projects, data analytics, to management. Throughout my career I've gained skills including design, test, computer programming, teamwork, and leadership. 

# I am most skilled in: <mark>Skill1</mark> and <mark>Skill2</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      # - layout: top-middle
      #   title: Advent of Code
      #   caption: October 2023 - Present
      #   additional_links:
      #     # - title:  anna-5765/aoc
      #     #   icon: fab fa-github
      #     #   url: github.com/anna-5765/aoc
      #    description: |
      #       A fun set of puzzles I try and complete to practice Python or learn a new programming language.
          
      - layout: top-middle
        title: Duckietown
        caption: November 2022 - November 2023
        # link: add link here
        # link_text: Project Website
        additional_links:
          - title:  anna-5765/duckietown-lx
            icon: fab fa-github
            url: github.com/anna-5765/duckietown-lx/tree/mooc2022
        description: | # this will include new lines to allow paragraphs
           

      - layout: top-middle
        title: Purdue Utility Project
        caption: November 2015 - June 2018
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
 
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Caterpillar
        link: 
        # link_text: (ex. cat.com)
        sub_title: NPI Coordinator - Operations Quality 
        caption: July 2021 - February 2023
       # quote: >
        description: | # this will include new lines to allow paragraphs
         I coordinated projects in Operations Quality related to new product at the Caterpillar Large Engine Center. This included facilitating 10+ major Process FMEA Risk Assessments, creating the cleanliness test process for a new insourced 3600 housing, validating the new housing's machining process per cleanliness standards through collecting and inspecting internal debris load data, and completing PFMEA action items as Quality representative during the runoff of a new automatic piston assembly cell.

      - layout: left
        sub_title: Leadership and Technical Development Rotational Program
        quote: >
         This is a Caterpillar Rotational Program in Manufacturing Engineering - essentially 3 different roles in 3 different locations over 3 years.

      - layout: left
        sub_title: |
           LTDP 3: Section Manager 
        caption: July 2020 - July 2021
        description: | # this will include new lines to allow paragraphs
         I worked as the 2nd shift manager of Outbound Logistics in 2020 and Point of Use in 2021. These were at the warehouse and engine remanufacturing facility respectively. The Outbound Logistics team is expected to pull, packout, stage, and ship material to remanufacturing campus facilities, while Point of Use to inbound, put up, and move material interfacility.

         As a section manager, I engaged in proactive safety through standard work audits, continuous improvement cards, and stop-to-fix incidents for out of process situations; investigated quality defects; communicated timely and effectively; managed manpower flexibility and onboarding; and tried to leverage my technical background by designing a helpful handtool for the putaway team. I did a lot of stuff every day, but I think the most important was listening to my employees and following up with them about their needs.
      
      - layout: left
        sub_title: |
           LTDP 2: Manufacturing Engineer 
        caption: July 2019 - July 2020
        description: | # this will include new lines to allow paragraphs
         This was my favorite role while working at Caterpillar. At the coupling machining and assembly center, I acted as line side support for troubleshooting newly installed semi-automatic assembly machines, led 4 capital projects procuring additional new machinery,  redid the chemical storage area layout and labeling per GHS & HMIS standards, calculated part cost analysis with Finance, labeled 20+ work bars for specific product usage at the rack plating line, and updated tool cards in the Microsoft Access database for bending and oven operations.
         
      - layout: left
        sub_title: |
           LTDP 1: Operations Quality Engineer 
        caption: July 2018 - July 2019
        description: | # this will include new lines to allow paragraphs
         I worked in a few different realms of Quality as an engineer at the Large Engine Center. While working in Supplier Quality, I created a webtool they still use today that crunches risk numbers based on leading indicators of a supplier part nonconformance, and aids in routing material through receiving inspection before being accepted into official Cat inventory. Within Internal Quality, I ran a machine shop metrology strategy project on the 3500 rod line, auditing and improving feature gauging details and data collection. Within Out-Plant Quality, I added 2 additional quality gates on the 3600 line through analyzing defect per unit data and ensuring the gate location in a close feedback loop relative to defect cause area.
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: |
          ETHx: ETH Zurich
        caption: November 2022 - November 2023
        sub_title: Self-Driving Cars with Duckietown
        quote: >
          Self-Driving Cars with Duckietown is a robotics and AI Massive Open Online Course hosted on edX, an online learning platform.
        description: | # this will include new lines to allow paragraphs
          I started this course as a way of improving my technical repertoire and learning about robotics and programming. Through an intense learning approach, I gained experience with professional tools and workflows used in modern robotics such as:
          - <mark>Linux</mark> 
          - Terminal interfaces
          - <mark>ROS</mark> 
          - <mark>Python</mark>
          - Computer vision & training <mark>Convolutional neural networks</mark>
          - <mark>GitHub</mark>
          - Incrementally developing solutions 
          - Creative troubleshooting
          - Testing solutions in simulation before the real world

          I also interacted with the community of peer learners and the staff on the course Slack and Stack Overflow. This includes asking for help and supporting others in answering peer questions.
      - layout: left
        title: Purdue University
        caption: August 2014 - May 2018
        sub_title: | 
          BS Mechanical Engineering
        # quote: >
        #   insert quote text
        description: | # this will include new lines to allow paragraphs
          During my time at Purdue I learned key skills that have I have taken through my career such as dedication, an intuition to how the science of the world works, and a curiosity to creativly problem-solve. I thouroughly enjoyed my time at university.

          I spent a lot of my free time working on the Purdue Utility Project global development team, advocating for student involvement in global engineering experiences as an Ambassador for Global Engineering Programs, and staying involved with other outreach organizations such as volunteering for Purdue Space Day, Introduce a Girl to Engineering, and Women in Engineering.

      - layout: left
        title: ESTACA
        caption: Spring 2017
        sub_title: Automotive & Aeronautics Design Program
        quote: >
          ESTACA (École Supérieure des Techniques Aéronautiques et de Construction Automobile) Paris campus offers this program to international applicants as a technical skill-centric program focusing on computer aided design and simulation.
        description: | # this will include new lines to allow paragraphs
          This was a study abroad semester for me that amplified my engineering basis as well as my cultural understandings.
          
          Modules included Computer Aided Design (<mark>CATIA</mark>), Signal Processing (<mark>Matlab</mark>), Computational Fluid Dynamics (<mark>STAR-CCM+</mark>), Hydraulic Systems (<mark>AmeSim</mark>), Structural Design (FEM Simulation with CATIA), Technical Project, and French Language and Culture.
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In 2023-2024 I took some time to pursue personal interests in life & career. Check out Duckietown in my projects section to learn more about my delve into robotics & autonomy.

      I also spent some time off-grid in the British Virgin Islands. I enjoy sailing and learning about boat systems, here are some photos of the adventure.

      <div class="image-container">
        <img src="/images/Sail_stern.jpeg" alt="BVIs off the stern">
        <img src="/images/Sail_helm.jpeg" alt="Helm station">
        <img src="/images/Sail_bow.jpeg" alt="En sail">
      </div>
      
# ![BVIs Stern](/images/Sail_stern.jpeg "BVIs Stern") ![BVIs Helm](/images/Sail_helm.jpeg "BVIs Helm")
      
# LINK EXAMPLE - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false
references_title:

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
